apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: semifir
            - name: MYSQL_DATABASE
              value: semifir
            - name: MYSQL_USER
              value: semifir
            - name: MYSQL_PASSWORD
              value: semifir
            - name: MARIADB_ROOT_PASSWORD
              value: semifir
          ports:
            - containerPort: 3306
              name: mariadb