apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactcicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactcicd
  template:
    metadata:
      labels:
        app: reactcicd
    spec:
      containers:
      - name: reactcicd
        image: ashram939/reactcicd:e093a8d6399951cb91ab20bd1f12dc91602a7276
        ports:
        - containerPort: 80
